name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: android-actions/setup-android@v3

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.37

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK
        run: |
          sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;35.0.0"

      - name: Remove old Buildozer cache
        run: rm -rf ~/.buildozer

      - name: Build APK
        env:
          BUILDOZER_WARN_ON_ROOT: 0
        run: |
          export ANDROID_HOME=$ANDROID_HOME
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROIDSDK=$ANDROID_HOME

          buildozer android debug

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: |
            .buildozer/**/*.log
            **/*.log
